action_id: trunk-single-player-auto-upgrade
date: 2025-04-08 10:28:00
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1744108080
full_timestamp:
  nanos: 803782000
  seconds: 1744108080
trunk_version: 1.22.12
