action_id: trunk-cache-prune
date: 2025-04-15 13:51:44
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1744725104
full_timestamp:
  nanos: 850986000
  seconds: 1744725104
trunk_version: 1.22.12
