action_id: trunk-cache-prune
date: 2025-04-08 09:18:02
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1744103882
full_timestamp:
  nanos: 117179000
  seconds: 1744103882
trunk_version: 1.22.12
