@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\madha\AppData\Local\trunk\tools\osv-scanner\2.0.1-ed37554d768ac63d823ce07697cbbddd;C:\Users\madha\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\madha\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
