@echo off
REM Generated by trunk tool 'prettier'
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\madha\AppData\Local\trunk\tools\prettier\3.5.3-afa23eb4b60aa9697da1e4a090874b93/node_modules/.bin;C:\Users\madha\AppData\Local\trunk\tools\node\18.20.5-730a53566ca346270d1e9ab4c1afaea8/bin;C:\Users\madha\AppData\Local\trunk\tools\node\18.20.5-730a53566ca346270d1e9ab4c1afaea8;C:\Users\madha\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\madha\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set NODE_PATH=C:\Users\madha\AppData\Local\trunk\tools\prettier\3.5.3-afa23eb4b60aa9697da1e4a090874b93/node_modules

start /w /b prettier %*
