@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\madha\AppData\Local\trunk\tools\trufflehog\3.88.24-cdf935bea4c80b3f5daf35406f5313bf;C:\Users\madha\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\madha\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
