@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\madha\AppData\Local\trunk\tools\trufflehog\3.88.23-f8bcf0338b01300b33c3cb7651d9604f;C:\Users\madha\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\madha\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
