const CommentsData = [
    {
      id: "1",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
      name: "Jessica Thompson",
      textContent: "This is amazing! I totally agree with your points.",
      timeAgo: "2m ago",
      likes: 86,
    },
    {
      id: "2",
      avatar: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "David Warner",
      textContent: "Interesting take. I hadn't thought of it that way!",
      timeAgo: "5m ago",
      likes: 45,
    },
    {
      id: "3",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
      name: "Emily Clarke",
      textContent: "Thanks for sharing this! Super helpful 💯",
      timeAgo: "10m ago",
      likes: 61,
    },
    {
    id: "1",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    name: "Jessica Thompson",
    textContent: "This is amazing! I totally agree with your points.",
    timeAgo: "2m ago",
    likes: 86,
  },
  {
    id: "2",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    name: "David Warner",
    textContent: "Interesting take. I hadn't thought of it that way!",
    timeAgo: "5m ago",
    likes: 45,
  },
  {
    id: "3",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    name: "Emily Clarke",
    textContent: "Thanks for sharing this! Super helpful 💯",
    timeAgo: "10m ago",
    likes: 61,
  },
  {
    id: "1",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    name: "Jessica Thompson",
    textContent: "This is amazing! I totally agree with your points.",
    timeAgo: "2m ago",
    likes: 86,
  },
  {
    id: "2",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    name: "David Warner",
    textContent: "Interesting take. I hadn't thought of it that way!",
    timeAgo: "5m ago",
    likes: 45,
  },
  {
    id: "3",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    name: "Emily Clarke",
    textContent: "Thanks for sharing this! Super helpful 💯",
    timeAgo: "10m ago",
    likes: 61,
  },
  {
  id: "1",
  avatar: "https://randomuser.me/api/portraits/women/44.jpg",
  name: "Jessica Thompson",
  textContent: "This is amazing! I totally agree with your points.",
  timeAgo: "2m ago",
  likes: 86,
},
{
  id: "2",
  avatar: "https://randomuser.me/api/portraits/men/12.jpg",
  name: "David Warner",
  textContent: "Interesting take. I hadn't thought of it that way!",
  timeAgo: "5m ago",
  likes: 45,
},
{
  id: "3",
  avatar: "https://randomuser.me/api/portraits/women/22.jpg",
  name: "Emily Clarke",
  textContent: "Thanks for sharing this! Super helpful 💯",
  timeAgo: "10m ago",
  likes: 61,
},

  ];
  
  export default CommentsData;
  