action_id: trunk-upgrade-available
date: 2025-04-08 13:05:43
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1744117543
full_timestamp:
  nanos: 932044000
  seconds: 1744117543
trunk_version: 1.22.12
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
