action_id: trunk-upgrade-available
date: 2025-04-08 10:18:24
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1744107504
full_timestamp:
  nanos: 293255000
  seconds: 1744107504
trunk_version: 1.22.12
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
