action_id: trunk-upgrade-available
date: 2025-04-09 06:15:37
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: ""
timestamp: 1744179337
full_timestamp:
  nanos: 748935000
  seconds: 1744179337
trunk_version: 1.22.12
