action_id: trunk-upgrade-available
date: 2025-04-16 04:34:48
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: ""
timestamp: 1744778088
full_timestamp:
  nanos: 405480000
  seconds: 1744778088
trunk_version: 1.22.12
