action_id: trunk-upgrade-available
date: 2025-04-16 05:32:58
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: ""
timestamp: 1744781578
full_timestamp:
  nanos: 655550000
  seconds: 1744781578
trunk_version: 1.22.12
