action_id: trunk-upgrade-available
date: 2025-04-08 12:05:59
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1744113959
full_timestamp:
  nanos: 214390000
  seconds: 1744113959
trunk_version: 1.22.12
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
