action_id: trunk-share-with-everyone
date: 2025-04-15 14:03:02
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1744725782
full_timestamp:
  nanos: 61497000
  seconds: 1744725782
trunk_version: 1.22.12
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
