action_id: trunk-share-with-everyone
date: 2025-04-17 05:36:50
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1744868210
full_timestamp:
  nanos: 910806000
  seconds: 1744868210
trunk_version: 1.22.12
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
